### ISSUE TITLE
Build status and doc status in readme is not pointing at anything

### ISSUE THREAD

**Issue by KPLauritzen** [dfds-data/denodoclient#7]
![image](https://user-images.githubusercontent.com/814491/113666257-4ff79180-96af-11eb-9822-5d2eb4c91ff1.png)

You should probably just remove this. Or even better, get documentation!

**Comment by martimors** [comment]
The docs are still WIP. Those badges stem from the cookiecutter template I used to scaffold the project, so it's probably a minor issue to fix them.
